import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import Navbar from "@/components/navbar";
import { Providers } from "./providers";
import { Head } from "next/document";

export const metadata = {
  title: "LightLink NFT Marketplace Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-gray-50">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700"
          rel="stylesheet"
        />
      </head>
      <body className="bg-[#000000]">
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
